"""Database type aliases — agents annotate against DBPool, not asyncpg.Pool."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DBPool(Protocol):
    """Structural type for an asyncpg connection pool.

    Agents annotate constructor params with ``DBPool`` instead of
    ``asyncpg.Pool`` so they don't need asyncpg as a direct import.
    The container registers the real pool under this key.
    """

    async def acquire(self) -> Any: ...
    async def release(self, conn: Any) -> None: ...
    async def execute(self, query: str, *args: Any, timeout: float | None = None) -> str: ...
    async def fetch(self, query: str, *args: Any, timeout: float | None = None) -> list[Any]: ...
    async def fetchrow(self, query: str, *args: Any, timeout: float | None = None) -> Any: ...
    async def fetchval(self, query: str, *args: Any, timeout: float | None = None) -> Any: ...
    async def close(self) -> None: ...
