#!/usr/bin/env bun
/**
 * Generates TypeScript types for @ze/client and @ze/ui from the Python backend.
 *
 * Usage:
 *   bun run scripts/codegen.ts
 *
 * Schemas are extracted directly from Python (no server needed).
 *
 * REST types: @hey-api/openapi-ts → sdk.gen.ts + types.gen.ts + client.gen.ts
 * WebSocket types: json-schema-to-typescript → ws.ts
 * UI contract: json-schema-to-typescript + ajv validators → packages/ze-ui/src/generated/
 */

import { execSync } from "child_process";
import { mkdirSync, writeFileSync, unlinkSync } from "fs";
import { join } from "path";
import { compile } from "json-schema-to-typescript";

const root = join(import.meta.dir, "..");
const clientGeneratedDir = join(root, "packages/ze-client/src/generated");
const uiGeneratedDir = join(root, "packages/ze-ui/src/generated");
const tmpSchema = join(clientGeneratedDir, ".openapi.tmp.json");

mkdirSync(clientGeneratedDir, { recursive: true });
mkdirSync(uiGeneratedDir, { recursive: true });

// ── 1. REST SDK from OpenAPI ─────────────────────────────────────────────────

console.log("Extracting OpenAPI schema from Python...");

const openapiJson = execSync(
  `cd ${root} && uv run --project apps/ze-api python -c "` +
    `import json; from ze_api.openapi_export import export_openapi; print(json.dumps(export_openapi()))"`,
  { encoding: "utf8" },
);

writeFileSync(tmpSchema, openapiJson);

console.log("Generating REST SDK (@hey-api/openapi-ts)...");

execSync(
  `cd ${root} && bunx openapi-ts -i ${tmpSchema} -o packages/ze-client/src/generated --client @hey-api/client-fetch --silent`,
  { stdio: "inherit" },
);

console.log("  → packages/ze-client/src/generated/ (sdk.gen.ts, types.gen.ts, client.gen.ts)");

try {
  unlinkSync(tmpSchema);
} catch {
  // ignore
}

// ── 2. WebSocket types from Pydantic ─────────────────────────────────────────

console.log("Extracting WebSocket schemas from Python...");

const wsSchemaJson = execSync(
  `cd ${root} && uv run --project apps/ze-api python -c "` +
    `import json; from pydantic import TypeAdapter; ` +
    `from ze_api.api.schemas import WsInboundFrame, WsOutboundFrame; ` +
    `inbound = TypeAdapter(WsInboundFrame).json_schema(); ` +
    `outbound = TypeAdapter(WsOutboundFrame).json_schema(); ` +
    `defs = {**inbound.pop('\\$defs', {}), **outbound.pop('\\$defs', {})}; ` +
    `defs['WsInboundFrame'] = inbound; defs['WsOutboundFrame'] = outbound; ` +
    `print(json.dumps({'\\$defs': defs, 'title': 'WsProtocol', 'type': 'object', ` +
    `'properties': {'inbound': {'\\$ref': '#/\\$defs/WsInboundFrame'}, 'outbound': {'\\$ref': '#/\\$defs/WsOutboundFrame'}}}))"`,
  { encoding: "utf8" },
);

const wsSchema = JSON.parse(wsSchemaJson) as Parameters<typeof compile>[0];

console.log("Generating WebSocket types (json-schema-to-typescript)...");

const wsTs = await compile(wsSchema, "WsProtocol", {
  bannerComment: "",
  additionalProperties: false,
  unreachableDefinitions: true,
  format: true,
});

writeFileSync(join(clientGeneratedDir, "ws.ts"), wsTs);
console.log("  → packages/ze-client/src/generated/ws.ts");

// ── 3. Server-driven UI contract for @ze/ui ────────────────────────────────

console.log("Extracting UI primitive schema from Python...");

const uiSchemaJson = execSync(
  `cd ${root} && uv run --project core/ze-components python -c "` +
    `import json; from ze_components.schema import export_json_schema; print(json.dumps(export_json_schema()))"`,
  { encoding: "utf8" },
);

const uiSchema = JSON.parse(uiSchemaJson) as Parameters<typeof compile>[0];

writeFileSync(join(uiGeneratedDir, "schema.json"), `${JSON.stringify(uiSchema, null, 2)}\n`);

console.log("Generating UI types (json-schema-to-typescript)...");

const uiTypesTs = await compile(uiSchema, "ZeUiPrimitives", {
  bannerComment: "// Generated by scripts/codegen.ts — do not edit manually.\n",
  additionalProperties: false,
  unreachableDefinitions: true,
  format: true,
});

writeFileSync(join(uiGeneratedDir, "types.gen.ts"), uiTypesTs);

const validatorsTs = `// Generated by scripts/codegen.ts — do not edit manually.

import Ajv2020 from "ajv/dist/2020";
import type { ErrorObject } from "ajv";
import schemaDocument from "./schema.json";

const ajv = new Ajv2020({ allErrors: true, strict: false, allowUnionTypes: true });

const primitiveValidator = ajv.compile({
  $schema: schemaDocument.$schema,
  $defs: schemaDocument.$defs,
  ...schemaDocument.$defs.Primitive,
});

const primitiveTreeValidator = ajv.compile({
  $schema: schemaDocument.$schema,
  $defs: schemaDocument.$defs,
  ...schemaDocument.$defs.PrimitiveTree,
});

export function runPrimitiveValidator(data: unknown): boolean {
  return primitiveValidator(data) as boolean;
}

export function runPrimitiveTreeValidator(data: unknown): boolean {
  return primitiveTreeValidator(data) as boolean;
}

export function primitiveValidationErrors(data: unknown): ErrorObject[] | null | undefined {
  primitiveValidator(data);
  return primitiveValidator.errors;
}

export function primitiveTreeValidationErrors(data: unknown): ErrorObject[] | null | undefined {
  primitiveTreeValidator(data);
  return primitiveTreeValidator.errors;
}
`;

writeFileSync(join(uiGeneratedDir, "validators.gen.ts"), validatorsTs);

const generatedIndexTs = `// Generated by scripts/codegen.ts — do not edit manually.

export * from "./types.gen";
export {
  primitiveTreeValidationErrors,
  primitiveValidationErrors,
  runPrimitiveTreeValidator,
  runPrimitiveValidator,
} from "./validators.gen";
export { default as uiSchema } from "./schema.json";
`;

writeFileSync(join(uiGeneratedDir, "index.ts"), generatedIndexTs);

console.log("  → packages/ze-ui/src/generated/ (schema.json, types.gen.ts, validators.gen.ts)");

console.log("\nCodegen complete.");
