#!/usr/bin/env python3
"""Generate JSON schema and TypeScript types from Python primitive types.

Usage:
    uv run scripts/generate_components.py

Outputs:
    docs/component-schema.json
    apps/ze-web/src/components/server-driven/types.ts
"""
from __future__ import annotations

import dataclasses
import json
import sys
import types
import typing
from pathlib import Path

repo_root = Path(__file__).parent.parent
sys.path.insert(0, str(repo_root / "core" / "ze-components"))
sys.path.insert(0, str(repo_root / "core" / "ze-core"))

from ze_components.schema import export_json_schema  # noqa: E402
from ze_components import PRIMITIVE_TYPES, PRIMITIVE_SUB_TYPES  # noqa: E402

_DOCS_DIR = repo_root / "docs"
_TS_OUT = repo_root / "apps" / "ze-web" / "src" / "components" / "server-driven" / "types.ts"

_PY_TO_TS: dict[type, str] = {
    str: "string",
    int: "number",
    float: "number",
    bool: "boolean",
}


def _unwrap_optional(annotation: type) -> tuple[type, bool]:
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin in (typing.Union, types.UnionType) and type(None) in args:
        non_none = [a for a in args if a is not type(None)]
        return (non_none[0] if non_none else str), True
    return annotation, False


def _ts_type(annotation: type, field_name: str = "") -> str:
    annotation, _ = _unwrap_optional(annotation)
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    # children fields on Col/Row carry Primitive trees
    if field_name == "children":
        return "Primitive[]"

    if annotation in _PY_TO_TS:
        return _PY_TO_TS[annotation]

    if annotation is list:
        return "unknown[]"

    if origin is list:
        item = args[0] if args else str
        return f"{_ts_type(item)}[]"

    if dataclasses.is_dataclass(annotation):
        return annotation.__name__

    if origin is typing.Literal:
        return " | ".join(f'"{v}"' for v in args)

    return "string"


def _ts_name(cls: type) -> str:
    return cls.__name__ + "Primitive"


def _emit_ts_interface(cls: type, lines: list[str], *, is_primitive: bool = False) -> None:
    hints = typing.get_type_hints(cls)
    init_fields = {f.name for f in dataclasses.fields(cls) if f.init}
    fields = [
        f for f in dataclasses.fields(cls)
        if f.name in init_fields or (is_primitive and f.name == "type")
    ]

    iface_name = _ts_name(cls) if is_primitive else cls.__name__
    lines.append(f"export interface {iface_name} {{")
    for field in fields:
        annotation = hints[field.name]
        inner, is_optional = _unwrap_optional(annotation)
        ts_t = _ts_type(annotation, field.name)

        origin = typing.get_origin(inner)
        is_literal = origin is typing.Literal

        has_default = (
            field.default is not dataclasses.MISSING
            or field.default_factory is not dataclasses.MISSING  # type: ignore[misc]
        )
        optional = is_optional or (has_default and not is_literal and field.name != "type")
        suffix = "?" if optional else ""
        lines.append(f"  {field.name}{suffix}: {ts_t};")
    lines.append("}")
    lines.append("")


def _emit_ts_types(out_path: Path) -> None:
    lines = [
        "// Generated by scripts/generate_components.py — do not edit manually.",
        "// Run `make generate-components` to regenerate.",
        "",
    ]

    for cls in PRIMITIVE_SUB_TYPES:
        _emit_ts_interface(cls, lines)

    for cls in PRIMITIVE_TYPES:
        _emit_ts_interface(cls, lines, is_primitive=True)

    lines.append("export type Primitive =")
    for i, cls in enumerate(PRIMITIVE_TYPES):
        sep = ";" if i == len(PRIMITIVE_TYPES) - 1 else ""
        lines.append(f"  | {_ts_name(cls)}{sep}")
    lines.append("")
    lines.append("// Alias kept for protocol.ts compat")
    lines.append("export type ComponentDescriptor = Primitive;")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"TypeScript types → {out_path}")


def main() -> None:
    _DOCS_DIR.mkdir(exist_ok=True)
    schema = export_json_schema()
    schema_path = _DOCS_DIR / "component-schema.json"
    schema_path.write_text(json.dumps(schema, indent=2))
    print(f"JSON schema → {schema_path}")

    if _TS_OUT.parent.exists():
        _emit_ts_types(_TS_OUT)
    else:
        print("ze-web not found — skipping TypeScript codegen")


if __name__ == "__main__":
    main()
