#!/usr/bin/env python3
"""Generate JSON schema and TypeScript types from Python component types.

Usage:
    uv run scripts/generate_components.py

Outputs:
    docs/component-schema.json
    apps/ze-web/src/components/types.ts
"""
from __future__ import annotations

import dataclasses
import json
import sys
import types
import typing
from pathlib import Path

repo_root = Path(__file__).parent.parent
sys.path.insert(0, str(repo_root / "core" / "ze-components"))
sys.path.insert(0, str(repo_root / "core" / "ze-core"))

from ze_components.schema import export_json_schema, _dataclass_schema
from ze_components.types import COMPONENT_TYPES, SUB_ITEM_TYPES

_DOCS_DIR = repo_root / "docs"
_TS_OUT = repo_root / "apps" / "ze-web" / "src" / "components" / "types.ts"

_PY_TO_TS: dict[type, str] = {
    str: "string",
    int: "number",
    float: "number",
    bool: "boolean",
}


def _unwrap_optional(annotation: type) -> tuple[type, bool]:
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin in (typing.Union, types.UnionType) and type(None) in args:
        non_none = [a for a in args if a is not type(None)]
        return (non_none[0] if non_none else str), True
    return annotation, False


def _ts_type(annotation: type) -> str:
    annotation, _ = _unwrap_optional(annotation)
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    if annotation in _PY_TO_TS:
        return _PY_TO_TS[annotation]

    if origin is list:
        item = args[0] if args else str
        return f"{_ts_type(item)}[]"

    if dataclasses.is_dataclass(annotation):
        return annotation.__name__

    # Literal type — emit a union of string literals
    if origin is typing.Literal:
        return " | ".join(f'"{v}"' for v in args)

    return "string"


def _emit_ts_interface(cls: type, lines: list[str]) -> None:
    hints = typing.get_type_hints(cls)
    fields = [f for f in dataclasses.fields(cls) if f.init]

    lines.append(f"export interface {cls.__name__} {{")
    for field in fields:
        annotation = hints[field.name]
        inner, is_optional = _unwrap_optional(annotation)
        ts_t = _ts_type(annotation)

        # Literal type discriminator — emit as literal, not optional
        origin = typing.get_origin(inner)
        is_literal = origin is typing.Literal

        has_default = (
            field.default is not dataclasses.MISSING
            or field.default_factory is not dataclasses.MISSING  # type: ignore[misc]
        )
        optional = is_optional or (has_default and not is_literal and field.name != "type")
        suffix = "?" if optional else ""
        lines.append(f"  {field.name}{suffix}: {ts_t};")
    lines.append("}")
    lines.append("")


def _emit_ts_types(out_path: Path) -> None:
    lines = [
        "// Generated by scripts/generate_components.py — do not edit manually.",
        "// Run `make generate-components` to regenerate.",
        "",
    ]

    for cls in SUB_ITEM_TYPES:
        _emit_ts_interface(cls, lines)

    for cls in COMPONENT_TYPES:
        _emit_ts_interface(cls, lines)

    union = " | ".join(cls.__name__ for cls in COMPONENT_TYPES)
    lines.append(f"export type ComponentDescriptor =")
    for i, cls in enumerate(COMPONENT_TYPES):
        sep = ";" if i == len(COMPONENT_TYPES) - 1 else ""
        prefix = "  | " if i > 0 else "  | "
        lines.append(f"{prefix}{cls.__name__}{sep}")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"TypeScript types → {out_path}")


def main() -> None:
    _DOCS_DIR.mkdir(exist_ok=True)
    schema = export_json_schema()
    schema_path = _DOCS_DIR / "component-schema.json"
    schema_path.write_text(json.dumps(schema, indent=2))
    print(f"JSON schema → {schema_path}")

    if _TS_OUT.parent.exists():
        _emit_ts_types(_TS_OUT)
    else:
        print("ze-web not found — skipping TypeScript codegen")


if __name__ == "__main__":
    main()
