DEFAULT_FACT_BUDGET_TOKENS: int = 200
DEFAULT_EPISODE_BUDGET_TOKENS: int = 500
DEFAULT_EVENT_BUDGET_TOKENS: int = 200
DEFAULT_PROCEDURE_BUDGET_TOKENS: int = 300
DEFAULT_PROFILE_BUDGET_TOKENS: int = 300

EPISODES_FETCH_LIMIT: int = 20
CONTRADICTION_THRESHOLD: float = 0.85
MERGE_SILENT_THRESHOLD: float = 0.95
MERGE_LLM_THRESHOLD: float = 0.85

UNREVIEWED_TTL_DAYS: int = 90
CONTRADICTED_TTL_DAYS: int = 30
EXPIRY_GRACE_DAYS: int = 7

EPISODE_RECENCY_DAYS: int = 14
EPISODE_ARCHIVE_DAYS: int = 7
EPISODE_ARCHIVE_BATCH: int = 20
EPISODE_MIN_ARCHIVE_BATCH: int = 10
SESSION_GROUPING_ENABLED: bool = True
MIN_SESSION_EPISODES: int = 3
MAX_SESSIONS_PER_RUN: int = 10

MODEL_SYNTHESIS: str = "anthropic/claude-haiku-4-5"

SESSION_SUMMARY_ENABLED: bool = True
SESSION_SUMMARY_CHECK_INTERVAL_MINUTES: int = 10
SESSION_SUMMARY_MIN_EPISODES: int = 2
SESSION_SUMMARY_MAX_SESSIONS_PER_RUN: int = 5
SESSION_SUMMARY_MAX_TRANSCRIPT_TOKENS: int = 6000
DEFAULT_SESSION_SUMMARY_BUDGET_TOKENS: int = 600
SESSION_SUMMARIES_FETCH_LIMIT: int = 10

FORGETTING_WEIGHT_THRESHOLD: float = 0.1
DREAM_JOB_TIMEOUT_SECONDS: int = 1800

NLI_CONTRADICTION_THRESHOLD: float = 0.60
NLI_ENTAILMENT_THRESHOLD: float = 0.70
NLI_LOWER_COSINE_BOUND: float = 0.60
NLI_GROUNDING_THRESHOLD: float = 0.30
NLI_WRITE_TIME_CHECK: bool = True
NLI_RETRIEVAL_RERANK: bool = True
NLI_RERANK_CANDIDATE_MULTIPLIER: int = 2
NLI_RERANK_MIN_CANDIDATES: int = 5

RELEVANCE_FLOOR_DEFAULT: float = 0.35
COMPOSITE_WEIGHT_SIMILARITY_DEFAULT: float = 0.6
COMPOSITE_WEIGHT_RECENCY_DEFAULT: float = 0.25
COMPOSITE_WEIGHT_CONFIDENCE_DEFAULT: float = 0.15
ENTITY_MATCH_CONSTANT_DEFAULT: float = 0.75
ENTITY_ANCHOR_ENABLED_DEFAULT: bool = True
LIVE_RERANK_ENABLED_DEFAULT: bool = True
LIVE_RERANK_CANDIDATE_LIMIT_DEFAULT: int = 20
LIVE_RERANK_TIMEOUT_MS_DEFAULT: int = 120
