DEFAULT_FACT_BUDGET_TOKENS: int = 200
DEFAULT_EPISODE_BUDGET_TOKENS: int = 500
DEFAULT_EVENT_BUDGET_TOKENS: int = 200
DEFAULT_PROCEDURE_BUDGET_TOKENS: int = 300
DEFAULT_PROFILE_BUDGET_TOKENS: int = 300

EPISODES_FETCH_LIMIT: int = 20
CONTRADICTION_THRESHOLD: float = 0.85
MERGE_SILENT_THRESHOLD: float = 0.95
MERGE_LLM_THRESHOLD: float = 0.85

UNREVIEWED_TTL_DAYS: int = 90
CONTRADICTED_TTL_DAYS: int = 30
EXPIRY_GRACE_DAYS: int = 7

EPISODE_RECENCY_DAYS: int = 14
EPISODE_ARCHIVE_BATCH: int = 20
EPISODE_MIN_ARCHIVE_BATCH: int = 10

MODEL_SYNTHESIS: str = "anthropic/claude-haiku-4-5"
