// Generated by scripts/generate_components.py — do not edit manually.
// Run `make generate-components` to regenerate.

export interface FormField {
  id: string;
  label: string;
  field_type: "text" | "textarea" | "number" | "date" | "select" | "multiselect" | "boolean" | "chips";
  placeholder?: string;
  options?: string[];
  required?: boolean;
  help_text?: string;
  default_value?: string;
}

export interface ConnectionEvidence {
  label: string;
  kind: string;
  date?: string;
  source?: string;
}

export interface ConnectionItem {
  summary: string;
  narrative: string;
  relation: string;
  confidence: number;
  evidence?: ConnectionEvidence[];
}

export interface ColPrimitive {
  children: Primitive[];
  gap: "none" | "sm" | "md" | "lg";
  variant: "default" | "card" | "section";
  type: "col";
}

export interface RowPrimitive {
  children: Primitive[];
  gap: "none" | "sm" | "md" | "lg";
  align: "start" | "center" | "end" | "between";
  type: "row";
}

export interface TextPrimitive {
  content: string;
  style: "heading" | "subheading" | "body" | "label" | "caption" | "code";
  color: "default" | "muted" | "success" | "warning" | "error";
  type: "text";
}

export interface BadgePrimitive {
  label: string;
  color: "default" | "success" | "warning" | "error" | "info";
  type: "badge";
}

export interface DividerPrimitive {
  type: "divider";
}

export interface SpacerPrimitive {
  size: "sm" | "md" | "lg";
  type: "spacer";
}

export interface ButtonPrimitive {
  label: string;
  action: string;
  style: "primary" | "secondary" | "danger";
  type: "button";
}

export interface ProgressBarPrimitive {
  value: number;
  label?: string;
  type: "progress";
}

export interface TablePrimitive {
  headers: string[];
  rows: string[][];
  title?: string;
  caption?: string;
  type: "table";
}

export interface FormPrimitive {
  id: string;
  title: string;
  fields: FormField[];
  type: "form";
}

export interface ConnectionsPrimitive {
  connections: ConnectionItem[];
  title?: string;
  type: "connections";
}

export type Primitive =
  | ColPrimitive
  | RowPrimitive
  | TextPrimitive
  | BadgePrimitive
  | DividerPrimitive
  | SpacerPrimitive
  | ButtonPrimitive
  | ProgressBarPrimitive
  | TablePrimitive
  | FormPrimitive
  | ConnectionsPrimitive;
