// Generated by scripts/generate_components.py — do not edit manually.
// Run `make generate-components` to regenerate.

export interface ListItem {
  text: string;
  subtext?: string;
  status?: string;
}

export interface TimelineEvent {
  time: string;
  title: string;
  description?: string;
}

export interface ProgressStep {
  label: string;
  status: "done" | "active" | "pending";
}

export interface ConfirmAction {
  label: string;
  value: string;
  style?: "primary" | "secondary" | "danger";
}

export interface FormField {
  id: string;
  label: string;
  field_type: "text" | "number" | "date" | "select";
  placeholder?: string;
  options?: string[];
}

export interface TableComponent {
  type: "table";
  headers: string[];
  rows: string[][];
  title?: string;
  caption?: string;
}

export interface MetricComponent {
  type: "metric";
  label: string;
  value: string;
  trend?: string;
  note?: string;
}

export interface ListComponent {
  type: "list";
  items: ListItem[];
  title?: string;
}

export interface TimelineComponent {
  type: "timeline";
  events: TimelineEvent[];
  title?: string;
}

export interface ProgressComponent {
  type: "progress";
  title: string;
  steps: ProgressStep[];
}

export interface ConfirmComponent {
  type: "confirm";
  prompt: string;
  actions: ConfirmAction[];
}

export interface FormComponent {
  type: "form";
  title: string;
  fields: FormField[];
}

export interface CardComponent {
  type: "card";
  body: string;
  title?: string;
  style?: "info" | "warning" | "success" | "error";
}

export type ComponentDescriptor =
  | TableComponent
  | MetricComponent
  | ListComponent
  | TimelineComponent
  | ProgressComponent
  | ConfirmComponent
  | FormComponent
  | CardComponent;
